param(
    [string]$OutputPath = "event/dungeon/db/migrations/20260330_event_dungeon_recreate_functions.sql"
)

$dbRoot = Split-Path -Parent $PSScriptRoot
$files = @(
    "functions/internal/evd_current_user_id.sql"
    "functions/internal/evd_add_item.sql"
    "functions/internal/evd_add_bucket_item.sql"
    "functions/internal/evd_remove_item.sql"
    "functions/internal/evd_remove_bucket_item.sql"
    "functions/internal/evd_get_cell.sql"
    "functions/internal/evd_set_cell.sql"
    "functions/internal/evd_add_log.sql"
    "functions/internal/evd_build_snapshot.sql"
    "functions/internal/evd_pick_weighted.sql"
    "items/effects/evd_item_effect_substitute_apply.sql"
    "items/effects/evd_item_effect_insurance_apply.sql"
    "items/effects/evd_item_effect_golden_contract_apply.sql"
    "items/effects/evd_item_effect_vault_box_apply.sql"
    "items/effects/evd_item_effect_escape_rope_use.sql"
    "items/effects/evd_item_effect_bomb_radar_use.sql"
    "items/effects/evd_item_effect_heal_hp_use.sql"
    "items/effects/evd_item_effect_reveal_stairs_use.sql"
    "items/effects/evd_item_effect_reveal_hazards_use.sql"
    "items/effects/evd_item_effect_reveal_bombs_use.sql"
    "items/effects/evd_item_effect_holy_grail_use.sql"
    "items/effects/evd_item_effect_increase_max_hp_use.sql"
    "items/effects/evd_item_effect_abyss_ticket_use.sql"
    "items/effects/evd_item_effect_golden_contract_settle_escape.sql"
    "items/effects/evd_item_effect_return_multiplier_bonus_on_escape_settle_escape.sql"
    "items/effects/evd_item_effect_vault_box_settle_death.sql"
    "items/effects/evd_item_effect_insurance_settle_death.sql"
    "items/effects/evd_item_effect_relic_shop_discount_plus_5pct_collect.sql"
    "items/effects/evd_item_effect_relic_carry_limit_plus_1_collect.sql"
    "items/effects/evd_item_effect_relic_return_multiplier_plus_0_05_collect.sql"
    "items/effects/evd_item_effect_relic_bomb_radar_always_collect.sql"
    "items/effects/evd_item_effect_relic_max_life_plus_1_collect.sql"
    "items/effects/evd_item_effect_relic_death_coin_keep_plus_2pct_collect.sql"
    "items/effects/evd_item_effect_relic_keep_unused_manual_on_death_collect.sql"
    "items/dispatch/evd_dispatch_apply_granted_item.sql"
    "items/dispatch/evd_collect_passive_modifiers.sql"
    "items/dispatch/evd_dispatch_use_item.sql"
    "items/dispatch/evd_dispatch_finish_run_escape_settlement.sql"
    "items/dispatch/evd_dispatch_finish_run_death_settlement.sql"
    "items/dispatch/evd_validate_item_effect_registry.sql"
    "functions/internal/evd_generate_floor.sql"
    "functions/internal/evd_get_floor_value.sql"
    "functions/internal/evd_compute_coin_pickup_bonus.sql"
    "functions/internal/evd_draw_pickup_item.sql"
    "functions/internal/evd_generate_shop_offers.sql"
    "functions/internal/evd_resolve_floor_shift.sql"
    "functions/internal/evd_try_consume_revival_charm.sql"
    "functions/internal/evd_start_run_load_context.sql"
    "functions/internal/evd_start_run_build_inventory.sql"
    "functions/internal/evd_start_run_create_initial_floor.sql"
    "functions/internal/evd_start_run_log.sql"
    "functions/internal/evd_resolve_move_tile.sql"
    "functions/internal/evd_finalize_move.sql"
    "functions/internal/evd_finish_run_calculate.sql"
    "functions/internal/evd_finish_run_restore_items.sql"
    "functions/internal/evd_finish_run_finalize.sql"
    "functions/rpc/evd_set_stock_item_set.sql"
    "functions/rpc/evd_buy_stock_item.sql"
    "functions/rpc/evd_start_run.sql"
    "functions/rpc/evd_finish_run.sql"
    "functions/rpc/evd_move.sql"
    "functions/rpc/evd_use_item.sql"
    "functions/rpc/evd_resolve_stairs.sql"
    "functions/rpc/evd_claim_altar_reward.sql"
    "functions/rpc/evd_shop_purchase.sql"
) | ForEach-Object { Join-Path $dbRoot $_ }

$header = @(
    "-- Generated by event/dungeon/db/scripts/build_event_dungeon_bundle.ps1"
    "-- Canonical source: event/dungeon/db/functions/internal + event/dungeon/db/functions/rpc + event/dungeon/db/items"
    "-- Retired helpers are intentionally excluded: evd_get_range_value, evd_random_int, evd_random_numeric"
    ""
)

$body = foreach ($file in $files) {
    if (-not (Test-Path $file)) {
        throw "Missing canonical SQL file: $file"
    }

    $relative = $file.Replace($dbRoot + [IO.Path]::DirectorySeparatorChar, "").Replace("\", "/")
    @(
        "-- BEGIN $relative"
        (Get-Content -Raw -Encoding UTF8 $file).TrimEnd()
        "-- END $relative"
        ""
    )
}

$content = ($header + $body) -join [Environment]::NewLine
Set-Content -Path $OutputPath -Value $content -Encoding utf8
Write-Output "Wrote $OutputPath"
